Feature/d bqueries
Syphi/try_shop pull request #1
Opened 2018-01-09 13:14 UTC by Syphi

2018-01-09 13:23 UTC, strelass requested changes

2018-01-09 13:23 UTC, strelass commented on .idea/Shop.iml
> +<?xml version="1.0" encoding="UTF-8"?>
эти файлы закешировалась в гите, посмотри как очистить кеш и запуш после того как почистишь

2018-01-09 13:57 UTC, strelass requested changes
добавь *.pyc в гитигнор и всё что не связано с твоим кодом, например alembic/__pycache__ и не забудь почистить кеш гита

2018-01-09 13:57 UTC, strelass commented on DBlogic/queries.py
> +        raw_sql = '''INSERT INTO category (cat_name, image, description, slug, parent_id)
Такая работа с бд подвержена sql иньекциям. если работаешь с raw sql и хочешь вписывать в него параметры всегда используй специализированные средства типа text. Лежит в основном пакете sqlalchemy.

2018-01-09 13:57 UTC, strelass commented on alembic/versions/f588fe06ce4f_alter_orders_table.py
> +# payment_type = sa.Enum('cash', 'card', name='payment_type', metadata=metadata)
удаляй лишние комментарии

2018-01-09 13:57 UTC, strelass commented on alembic/versions/f588fe06ce4f_alter_orders_table.py
> +    pass
почему нет downgrade?

2018-01-09 13:57 UTC, strelass commented on alembic/versions/f588fe06ce4f_alter_orders_table.py
> +    op.alter_column('orders', 'payment_type', type_=sa.Enum('cash', 'card', name='payment_type'),
Принято значения енама писать капсом

p.s. `sa.dialects.postgresql.ENUM('cash', 'card', name='payment_type')` вот так можно

2018-01-09 14:09 UTC, Syphi commented on alembic/versions/f588fe06ce4f_alter_orders_table.py
> +    pass
это там где я не правильно абсолютно создал таблицу 
и я подумал что не надо откатывать на это

2018-01-09 14:11 UTC, Syphi commented on alembic/versions/f588fe06ce4f_alter_orders_table.py
> +    op.alter_column('orders', 'payment_type', type_=sa.Enum('cash', 'card', name='payment_type'),
как лучше писать?

2018-01-09 14:21 UTC, Syphi commented
я вот еще хотел спросить 
я же начал через raw sql делать 
но потом кже использовал sqlalcemy core 
тогда мне удалить ту файли с raw sql?

2018-01-09 14:36 UTC, strelass requested changes

2018-01-09 14:36 UTC, strelass commented on DBlogic/sqlal_queries.py
> +    def __init__(self):
Насчёт этого идея такая.
1. создай файл, в котором ты будешь хранить конфигурацию: имя базы, логин, пароль.
2. в точке входа в программу (__main__) нужно читать этот файл, доставать оттуда все параметры и с помощью этих параметров инициализировать приложение (в твоём случае это класс для работы с базой)

2018-01-09 14:36 UTC, strelass commented on DBlogic/sqlal_queries.py
> +        self.connection.execute(insert)
обычно после добавления записей пользователю хоть что-то возвращается, предлагаю возвращать весь вставленный объект. Посмотри как использовать метод **returning**

2018-01-09 14:36 UTC, strelass commented on DBlogic/sqlal_queries.py
> +            self.order_products = sa.Table('order_products', self.metadata, autoload=True, autoload_with=self.db)
Посмотри метод **reflect** в MetaData и сделай загрузку всех таблиц через него.

2018-01-09 14:36 UTC, strelass commented on DBlogic/sqlal_queries.py
> +    def add_product(self, category_id, prod_name, image, description, slug, price_ua, in_stock, other_info):
У тебя не все поля обязательные, зачем заставлять передавать их все?

2018-01-09 14:36 UTC, strelass commented on DBlogic/sqlal_queries.py
> +        # add to orders table
Если пишешь комментарии такого типа то делай либо по стандарту https://www.python.org/dev/peps/pep-0257/ , либо не делай вообще. И не стоит оставлять очевидные комментарии, вроде дублирования названия функции.

2018-01-09 14:36 UTC, strelass commented on DBlogic/sqlal_queries.py
> +    def add_orders(self, customer_id, sum_price, delivery_data_time, payment_type, dict):
Старайся не использовать зарезервированные слова, это сбивает с толку и усложняет читаемость кода.

2018-01-09 14:36 UTC, strelass commented on DBlogic/sqlal_queries.py
> +        self.connection.execute(insert, insert_list)
Представь ситуацию, когда сработал вызов этого метода, заказ создался, а после этого выключился свет. В таком случае товары не будут добавлены (конкретно на этом примере ничего страшного нет, но если пойдёт речь о денежных операциях это будет серьёзной угрозой). Посмотри что такое транзакции в бд, что они дают и когда их нужно использовать.

2018-01-09 14:36 UTC, strelass commented on DBlogic/sqlal_queries.py
> +    def get_category(self):
название метода не соответствует функционалу

2018-01-09 14:36 UTC, strelass commented on DBlogic/sqlal_queries.py
> +        result = self.connection.execute(select).fetchall()
id уникальный, лучше использовать fetchone вместо fetchall

2018-01-09 14:36 UTC, strelass commented on DBlogic/sqlal_queries.py
> +        while result[0][-1] != None:
Непонятная логика. У тебя же есть поле parent_id зачем ты проверяешь id? Здесь должен быть селект с одним where.

2018-01-09 14:36 UTC, strelass commented on DBlogic/sqlal_queries.py
> +    def get_subcategory(self, category_id):
название метода не соответствует функционалу

2018-01-09 14:36 UTC, strelass commented on DBlogic/sqlal_queries.py
> +        client_info = self.connection.execute(select).fetchall()[0]
Тебе не нужен объект customer для этого селекта, достаточно одного поля id. Проверка на существование кастомера должна быть где-то во view а не тут.

2018-01-09 14:36 UTC, strelass commented on DBlogic/sqlal_queries.py
> +        for order in orders_lst:
Это лишняя логика в этом методе. Лучше сделать отдельный метод для получения информации о конкретном заказе или о списке заказов.

2018-01-09 14:36 UTC, strelass commented on DBlogic/sqlal_queries.py
> +    def get_customer_from_login_and_password(self, login, password):
get_customer_by_login_and_password

2018-01-09 14:36 UTC, strelass commented on DBlogic/sqlal_queries.py
> +        return self.connection.execute(select).fetchall()
fetchone

2018-01-09 14:36 UTC, strelass commented on DBlogic/sqlal_queries.py
> +    def update_category(self, cat_name_old, cat_name_new, image_new, description_new, slug_new, parent_id_new):
Набор параметров для апдейта должен быть кастомный. Обязательно должно быть значение по которому мы сможем определить какую запись нужно обновить, т.е. **id**, а дальше лучше использовать `**kwargs`

2018-01-09 14:36 UTC, strelass commented on DBlogic/sqlal_queries.py
> +        self.connection.execute(update)
тоже самое, нужно возвращать новый обьект

2018-01-09 14:36 UTC, strelass commented on DBlogic/sqlal_queries.py
> +    def update_orders(self, order_id, new_customer_id, new_sum_price, new_delivery_data_time, new_payment_type, new_dict):
название метода не соответствует

2018-01-09 14:36 UTC, strelass commented on DBlogic/sqlal_queries.py
> +        for key, value in new_dict.items():
нужно вынести эту логику в отдельный метод

2018-01-09 14:36 UTC, strelass commented on DBlogic/sqlal_queries.py
> +    def delete_customer(self, id_customer):
в delete с параметром лучше использовать raw sql

2018-01-09 14:36 UTC, strelass commented on DBlogic/sqlal_queries.py
> +# test.add_category('name2', '//pass2//', '2description2', 'slug2', 1)
почему не использовал pytest для тестов?

2018-01-09 14:37 UTC, strelass commented on alembic/versions/f588fe06ce4f_alter_orders_table.py
> +    op.alter_column('orders', 'payment_type', type_=sa.Enum('cash', 'card', name='payment_type'),
я не знаю что получается в базе в твоём случае, если тоже самое то разницы нет, делай так как удобно

2018-01-09 14:39 UTC, strelass commented on alembic/versions/f588fe06ce4f_alter_orders_table.py
> +    pass
если ты её неправильно создал в рамках одного пра, то ты можешь внести правки в файл со стартовой миграцией, если создаёшь новую, то downgrade обязательно должен быть

2018-01-09 14:40 UTC, strelass commented
Да, лишнее нужно удалить

p.s. Я не могу отвечать на такие комментарии так что пиши в телегу или под моими замечаниями.

2018-01-10 17:14 UTC, Syphi commented on DBlogic/sqlal_queries.py
> +    def get_subcategory(self, category_id):
а как мне делать 
какой уровень вложености должен быть? 
мне выводить подкатегории для всех подкатегорий 
или хватит списка всех всех категорий у которих родительская категория, ту которую мы передаем?

2018-01-12 14:48 UTC, Syphi commented
![image](https://user-images.githubusercontent.com/17815623/34880191-558635c8-f7b8-11e7-8699-ae1213d20a07.png)

2018-01-16 12:48 UTC, strelass requested changes
Удалить из репозитория все *.pyc файлы

2018-01-16 12:48 UTC, strelass commented on .cache/v/cache/lastfailed
> +}
добавить весь кеш в гитигнор

2018-01-16 12:48 UTC, strelass commented on DBlogic/sqlal_queries.py
> +    filename = '/home/lenin/PycharmProjects/Shop/config/' + filename + '.txt'
txt лишнее, не обязательно давать файлу расширение. путь должен быть относительно проекта, у меня по этому пути ничего не лежит

2018-01-16 12:48 UTC, strelass commented on DBlogic/sqlal_queries.py
> +            self.db_string = 'postgresql://' + conf_lst[1] + ':' + conf_lst[2] + '@localhost/' + conf_lst[0]
host тоже должен быть параметром конфига

2018-01-16 12:48 UTC, strelass commented on DBlogic/sqlal_queries.py
> +    def __init__(self, conf_lst):
здесь лучше указать параметры явно

2018-01-16 12:48 UTC, strelass commented on DBlogic/sqlal_queries.py
> +        except Exception as e:
тут может быть только одна ошибка - ошибка подключения к бд, нужно отлавливать именно её

2018-01-16 12:48 UTC, strelass commented on DBlogic/sqlal_queries.py
> +                self.tables[key] = sa.Table(str(key), self.metadata, autoload=True, autoload_with=self.db)
этот код вынести в отдельную функцию

2018-01-16 12:48 UTC, strelass commented on DBlogic/sqlal_queries.py
> +        insert = sa.insert(self.tables['category']).returning(self.tables['category'])
предлагаю сделать отдельную функцию, которая будет возвращать таблицу по её названию и использовать её везде

2018-01-16 12:48 UTC, strelass commented on DBlogic/sqlal_queries.py
> +    def add_product(self, category_id, prod_name, slug, price_ua, in_stock, image='', description='', other_info=json):
json название библиотеки, лучше использовать другое название для переменной

2018-01-16 12:48 UTC, strelass commented on DBlogic/sqlal_queries.py
> +    def add_orders(self, customer_id, sum_price, dictionary_with_products, delivery_data_time=None, payment_type=None):
мне кажется тут ничего не поменялось из того о чём мы говорили

2018-01-16 12:48 UTC, strelass commented on DBlogic/sqlal_queries.py
> +    def get_subcategories_by_id(self, category_id):
неудачное название

2018-01-16 12:48 UTC, strelass commented on DBlogic/sqlal_queries.py
> +        print(result)
что здесь делает print?

2018-01-16 12:48 UTC, strelass commented on DBlogic/sqlal_queries.py
> +        print(self.connection.execute(select).fetchall())
убрать все принты

2018-01-16 12:48 UTC, strelass commented on DBlogic/sqlal_queries.py
> +    def get_order_info_from_order_id(self, order_id):
by_order_id

2018-01-16 12:48 UTC, strelass commented on DBlogic/sqlal_queries.py
> +            update = self.tables['order_products'].update().returning(self.tables['order_products'])
Этот update должен обновлять только запись в таблице `orders`. Для обновления записи в таблице `order_products` должен быть другой метод с такой сигнатурой 
`update_order_product(order_id, product_id, **kwargs)`

2018-01-16 12:48 UTC, strelass commented on DBlogic/sqlal_queries.py
> +                self.delete_order(res)
Для того, чтобы не заниматься таким есть в SQL такой параметр для внешних ключей как ON DELETE. Можешь указать там SET NULL или CASCADE и все записи подчистятся автоматом.

2018-01-16 12:48 UTC, strelass commented on DBlogic/sqlal_queries.py
> +# result = DB.add_category(cat_name='name_cat--', image_pass='//pass2//',
убрать отсюда комментарии, у тебя уже есть тест

2018-01-16 12:48 UTC, strelass commented on test/test_sqlal_queries.py
> +def test_update_category():
Тут нужно написать 2 разных варианта
1. с использованием yeild fixture
2. написать котекстный менеджер для получение конекшена

2018-01-16 12:48 UTC, strelass commented on test/test_sqlal_queries.py
> +               (19, 'new_cat_name', '//pass2//', '2description2', 'slug_update', 1)
убрать id из assert, лучше писать так
```
to_update = {
   'slug': 'new_slug'
}
r = DB.update_category(id_, **to_update)
assert r['slug'] == to_update['slug']
```
Нужно проверять только то, что относится к этому тесту. Для того, чтобы не придумывать свои id каждый раз в тест для update нужно добавить и insert тоже, следовательно логично делать это одним тестом.

2018-01-16 14:04 UTC, Syphi commented on DBlogic/sqlal_queries.py
> +        insert = sa.insert(self.tables['category']).returning(self.tables['category'])
это сделать при инициализации, и инициализировать все таблицы разом? 
или отдельно в каждей функции инициализировать таблицу?

2018-01-16 14:20 UTC, strelass commented on DBlogic/sqlal_queries.py
> +        insert = sa.insert(self.tables['category']).returning(self.tables['category'])
таблицы ты и так инициализируешь сразу, тут нужен просто гетер из дикта, чтобы вместо `self.tables['table_name']` писать `table = self.get_table('table_name')`

2018-01-18 15:55 UTC, Syphi commented on DBlogic/sqlal_queries.py
> +    def add_orders(self, customer_id, sum_price, dictionary_with_products, delivery_data_time=None, payment_type=None):
я тут удалил коментарии

2018-01-19 08:49 UTC, strelass requested changes

2018-01-19 08:49 UTC, strelass commented on DBlogic/sqlal_queries.py
> +    filename = os.path.abspath(__file__).replace('DBlogic', 'config').replace('sqlal_queries.py', filename)
раз уж взялся за os так делай через os.path.join и os.path.dirname

2018-01-19 08:49 UTC, strelass commented on DBlogic/sqlal_queries.py
> +                result.append(data[2])
3 раза повторил код

2018-01-19 08:49 UTC, strelass commented on DBlogic/sqlal_queries.py
> +            print('shit - no such db')
лучше убрать ругательства из кода

2018-01-19 08:49 UTC, strelass commented on DBlogic/sqlal_queries.py
> +                               'description': str(description), 'slug': str(slug), 'price_ua': price_ua,
настало время поговорить про slug, обычно его генерируют из названия обьекта, чтобы потом создать страничку таким url, типа /product/shokoladnoe-moloko , из этого следует несколько правил
1. формируем slug из названия (есть такая либа python-slugify предлагаю использовать её)
2. slug должен быть уникальным, т.к. не может один url вести на 2 разные страницы
3. ограничить slug по длинне, т.к. при переводе названия в slug длинна не всегда совпадает, а нам нужно чтобы это не вылезло за границы поля в бд
4. при обновлении записи в бд, нужно обновлять slug если изменилось название, если не изменилось slug не менять

2018-01-19 08:49 UTC, strelass commented on DBlogic/sqlal_queries.py
> +        select = order_table.select()
зачем этот селект?

2018-01-19 08:49 UTC, strelass commented on DBlogic/sqlal_queries.py
> +    def get_child_categories_for_category_by_id(self, category_id):
слишком сложное название, достаточно get_subcategories

2018-01-19 08:49 UTC, strelass commented on DBlogic/sqlal_queries.py
> +        for key, value in kwargs.items():
зачем этот цикл, что может быть в kwargs?

2018-01-19 08:49 UTC, strelass commented on test/test_2.py
> +    to_update = {'slug': 'new_slug'}
1. kwargs вынести в отдельную переменну.
2. после вставки в бд нужно проверить что запись создана с теми данными, которые мы ожидаем

2018-01-19 08:49 UTC, strelass commented on test/test_2.py
> +    DB.delete_customer(4)
магическое число 4

2018-01-19 08:49 UTC, strelass commented on test/test_2.py
> +    assert DB.get_customer_by_login_and_password('Denis2', '2qwerty2') == \
откуда в бд этот пользователь? у меня такого нет

2018-01-23 08:56 UTC, strelass requested changes

2018-01-23 08:56 UTC, strelass commented on DBlogic/sqlal_queries.py
> +                raise ValueError("Such slug already exists.")
тут не должно быть никакой ошибки, ты должен корректно отрабатыват ь такую ситуацию и генерить другой слаг например `slug-1`

2018-01-23 08:56 UTC, strelass commented on test/test_2.py
> +                'parent_id': 1}
откуда parent_id? откуда в базе другая категория?

2018-01-23 08:56 UTC, strelass commented on test/test_sqlal_queries.py
> +        self.init_dict = sq.read_from_file(self.filename)
filename и init_dict используюстя только в __init__ не стоит их хранить в полях класса

2018-01-23 10:44 UTC, strelass requested changes

2018-01-23 10:44 UTC, strelass commented on DBlogic/sqlal_queries.py
> +                    list_slug = list(slug)
со строками тоже можно так работать не обязательно перегонять в список

2018-01-23 10:44 UTC, strelass commented on DBlogic/sqlal_queries.py
> +                    list_slug[18:20] = random.randint(0, 99)
рандом не подходит, можешь нарандомить тот что уже есть

2018-01-24 12:59 UTC, strelass requested changes

2018-01-24 12:59 UTC, strelass commented on DBlogic/sqlal_queries.py
> +                   slug = '{}{}{}'.format(slug[:17], '-', self.inc_slug())
`f'{slug[:17]}-{self.inc_slug()}'` если уже на то пошло
inc_slug не пойдёт, если ты перезапустишь сервис у тебя обнулится переменная, нужно каждый раз всё перебирать

2018-01-24 12:59 UTC, strelass commented on DBlogic/sqlal_queries.py
> +                    slug = '{}{}{}'.format(slug, '-', self.inc_slug())
соответственно если такой слаг свободен, то к нему не нужно цеплять никаких цифр

2018-01-24 12:59 UTC, strelass commented
почитай best practice по формированию слага

2018-01-24 15:05 UTC, strelass commented on DBlogic/sqlal_queries.py
> +        print(slug)
1. если в таблице будет миллиард строк, ты каждый раз будешь полностью выгружать её в память
2. если ты попытаешься вызвать эту функцию при обновлении записи, то у тебя сгенерится новый слаг, т.к. в твоём селекте будет уже существующая запись в бд
3. этот if никчему - `slug[:17]` будет работать для списка любой длинны

2018-01-25 09:29 UTC, strelass requested changes

2018-01-25 09:29 UTC, strelass commented on DBlogic/sqlal_queries.py
> +        # print('Close class and connection')
ты уже определись оставить или удалить

2018-01-25 09:29 UTC, strelass commented on DBlogic/sqlal_queries.py
> +            select = sa.select([table.c.slug]).where(table.c.slug.like(f'%{txt}%'))
выше полное сравнение, тут LIKE да и зачем плодить одинаковый код, используй цикл while

2018-01-25 09:29 UTC, strelass commented on DBlogic/sqlal_queries.py
> +        if len(result) == 0:
лучше использовать exists из бд

2018-01-25 12:36 UTC, strelass approved these changes

2018-01-25 12:37 UTC, merged